---
title: "Initial Review Checklist"
output: github_document
---

- [ ] **Title:** Provides the *what, where, and when* of the data
- [ ] **Abstract:** Minimum 100 words.
- [ ] **Data files:** No xls/xlsx files. All attributes are defined (in methods or in email). Column names do not use spaces or special characters.  NA's are defined.
- [ ] **Contact information:** At least one contact with email and orcid
- [ ] **Temporal/geographic coverage:** Includes coverage that makes sense.
- [ ] **Funding:** At least one funding number
- [ ] **Methods:** enough detail should be provided that a reasonable scientist could effectively reuse and interpret the data. Submissions should:
- provide instrument names
- specify how sampling locations were chosen
- provide citations for sampling methods that are not explained in detail

- [ ] **
- [ ] **

## Starting email text

Hello _____,
Thank you for your recent submission to the NSF Arctic Data Center. We will review your dataset and get back to you with any suggestions.

From my preliminary examination of your submission I have noticed a few items that I would like to bring to your attention. We are happy to make any edits for you. See comments below:

[COMMENTS HERE]

Best,
[YOUR NAME]

## Title
- [ ] Provides the *what, where, and when* of the data

We would like to add some more context to your data set title. A descriptive title that provides context about the where, what, and when of a dataset is often far more useful in search results. Something like: ‘OUR SUGGESTION HERE, WHERE, WHEN’ might be an option.

## Abstract
- [ ] Minimum 100 words.

Your abstract, while informative, appears to be missing some information. We suggest that the abstract be sufficiently descriptive for a general scientific audience. It should provide an overview of the scientific context/ project/ hypotheses, how this data set fits into the larger project, a synopsis of the experimental or sampling design, and a summary of the data contents. If you prefer and it is appropriate, we could add language from the abstract in the NSF Award found here: https://www.nsf.gov/awardsearch/showAward?AWD_ID=#######&HistoricalAwards=false

## Data files
- [ ] No xls/xlsx files. All attributes are defined (in methods or in email). Column names do not use spaces or special characters.  NA's are defined.

We noticed that the data files submitted are in _____ format. We recommend conversion of these files into a plain text/csv (OR ANOTHER APPROPRIATE OPEN-SOURCE) format in order to facilitate an accurate transfer of information to future researchers and ensure preservation of the data in perpetuity. We will perform these conversions for you. Below are some linked articles about data science best practices that the NSF Arctic Data Center adheres to:
DataONE - https://www.dataone.org/best-practices “Some Simple Guidelines for Effective Data Management” - http://onlinelibrary.wiley.com/doi/10.1890/0012-9623-90.2.205/full “Good Enough Practices in Scientific Computing” - http://arxiv.org/pdf/1609.00037v1.pdf

We noticed that the data files contain… -blank cells. What do these represent? -some column headers that are unclear. Please define “X”. -some abbreviations that are unclear. Please define “XYZ”, including the unit of measure. -columns whose units are unclear. What are the units of measurement for the columns labeled “ABC” and “XYZ”?

We noticed that no data files were submitted. With the exception of sensitive social science data, NSF requires the submission of all data products prior to publication. Do you intend to submit data files?

## Contacts
- [ ] At least one contact with email and orcid


## Temporal/geographic coverage
- [ ] Includes coverage that makes sense.


## Funding
- [ ] **Funding:** At least one funding number


## Methods
- [ ] Enough detail should be provided that a reasonable scientist could effectively reuse and interpret the data. Submissions should:
- provide instrument names
- specify how sampling locations were chosen
- provide citations for sampling methods that are not explained in detail

Your methods, while informative, appear to be missing some information. Enough detail should be included so that a reasonable scientist can replicate the study without consulting you nor any other resources. This should hold true today, or even decades or a century from now. Users need to understand how the data were collected, how to interpret the values, and potentially how to use the data in the case of specialized files. We would be happy to add more content for you. Please provide us with a more robust methods section directly in this email or point us to a document from which we can extract more methods.


## Sources:
https://github.nceas.ucsb.edu/KNB/arctic-data/blob/master/PI_guidelines/Submission_Guidelines_for_PI.pdf
